#!/usr/bin/env bash
#
# oops.sh — creates a handful of random files for testing.
#
# Usage:
#   ./oops.sh              # 5 files in /Users/nick/Test
#   ./oops.sh 20           # 20 files
#   OOPS_DIR=/tmp/foo ./oops.sh 3
#

set -euo pipefail

TARGET_DIR="${OOPS_DIR:-/Users/nick/Test}"
COUNT="${1:-5}"

case "$COUNT" in
  ''|*[!0-9]*) echo "error: file count must be a number" >&2; exit 1 ;;
esac

mkdir -p "$TARGET_DIR"

EXTS=(txt log json csv md dat)
STAMP="$(date +%Y%m%d-%H%M%S)"

for i in $(seq 1 "$COUNT"); do
  ext="${EXTS[$((RANDOM % ${#EXTS[@]}))]}"
  rand="$(LC_ALL=C tr -dc 'a-z0-9' </dev/urandom | head -c 8)"
  file="${TARGET_DIR}/oops-${STAMP}-${i}-${rand}.${ext}"

  # a few hundred bytes to a few KB of random-ish content
  {
    echo "# generated by oops.sh at $(date -u +%FT%TZ)"
    echo "# file ${i} of ${COUNT}"
    LC_ALL=C tr -dc 'a-zA-Z0-9 \n' </dev/urandom | head -c "$((RANDOM % 4096 + 256))"
    echo
  } >"$file"

  echo "created: $file"
done

echo "Done — ${COUNT} file(s) in ${TARGET_DIR}"
